"""SQLAlchemy model for application user accounts."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sqlalchemy import Boolean, CheckConstraint, String, UniqueConstraint, text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.enums import UserRole
from src.models.base import Base, TimestampMixin, UUIDMixin, VersionMixin

if TYPE_CHECKING:
    from src.models.player import Player


class User(UUIDMixin, TimestampMixin, VersionMixin, Base):
    """A coach or player account managed by an administrator.

    Email addresses are normalized to lowercase before persistence. The
    ``hashed_password`` column stores only server-generated Argon2id output.
    """

    __tablename__ = "users"
    __table_args__ = (
        UniqueConstraint("email", name="uq_users_email"),
        CheckConstraint(
            "role IN ('head coach', 'assistant coach', 'player')",
            name="ck_users_role",
        ),
    )

    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    email: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="Lowercase-normalized account email address.",
    )
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="Argon2id password hash generated by the backend.",
    )
    role: Mapped[UserRole] = mapped_column(String(20), nullable=False)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    player_profile: Mapped[Player | None] = relationship(
        back_populates="user",
        uselist=False,
    )
