/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Business Audit Log
         * @description Return a validated, filtered, deterministic page of business events.
         */
        get: operations["get_business_audit_log_api_v1_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-log/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Business Audit Actor Options
         * @description Return bounded, deduplicated historical actor snapshots.
         */
        get: operations["get_business_audit_actor_options_api_v1_audit_log_actors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-log/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recent Business Activity
         * @description Return the latest one to four immutable business events.
         */
        get: operations["get_recent_business_activity_api_v1_audit_log_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditActionCategory
         * @description Business domains represented in the academy activity history.
         * @enum {string}
         */
        AuditActionCategory: "coach" | "player" | "team" | "roster" | "calendar" | "scoring";
        /**
         * AuditActionType
         * @description Stable identifiers for the initial business-audit action catalogue.
         * @enum {string}
         */
        AuditActionType: "coach.created" | "coach.activated" | "coach.deactivated" | "coach.team_assignments_updated" | "player.created" | "player.updated" | "player.account_linked" | "player.account_unlinked" | "player.account_reassigned" | "team.created" | "team.updated" | "roster.added" | "roster.removed" | "roster.reordered" | "calendar.standalone_created" | "calendar.standalone_updated" | "calendar.standalone_deleted" | "calendar.series_created" | "calendar.series_updated" | "calendar.series_deleted" | "calendar.occurrence_updated" | "calendar.occurrence_moved" | "calendar.occurrence_deleted" | "scoring.initialized" | "scoring.innings_started" | "scoring.delivery_corrected";
        /**
         * AuditEntityType
         * @description Historical target kinds supported by the business-audit feed.
         * @enum {string}
         */
        AuditEntityType: "coach" | "player" | "team" | "roster" | "calendar_event" | "recurrence_series" | "match";
        /**
         * BusinessAuditActorOption
         * @description One historical actor snapshot available as a bounded filter option.
         */
        BusinessAuditActorOption: {
            /** Actor Display Name */
            actor_display_name: string;
            /** Actor Role */
            actor_role: string | null;
            /**
             * Actor User Id
             * Format: uuid
             */
            actor_user_id: string;
        };
        /**
         * BusinessAuditActorOptionsResponse
         * @description At most 100 distinct actor snapshots.
         */
        BusinessAuditActorOptionsResponse: {
            /** Actors */
            actors: components["schemas"]["BusinessAuditActorOption"][];
        };
        /**
         * BusinessAuditEventResponse
         * @description Stored snapshots and allowlisted detail exposed by the API.
         */
        BusinessAuditEventResponse: {
            action_category: components["schemas"]["AuditActionCategory"];
            action_type: components["schemas"]["AuditActionType"];
            /** Actor Display Name */
            actor_display_name: string | null;
            /** Actor Role */
            actor_role: string | null;
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["BusinessAuditMetadataValue"];
            };
            /** Request Id */
            request_id: string | null;
            /** Summary */
            summary: string;
            /** Target Entity Id */
            target_entity_id: string | null;
            target_entity_type: components["schemas"]["AuditEntityType"];
            /** Target Label */
            target_label: string | null;
        };
        BusinessAuditMetadataScalar: string | number | boolean | null;
        BusinessAuditMetadataValue: components["schemas"]["BusinessAuditMetadataScalar"] | components["schemas"]["BusinessAuditMetadataScalar"][];
        /**
         * BusinessAuditPageResponse
         * @description One stable server-paginated business-audit page.
         */
        BusinessAuditPageResponse: {
            /** Events */
            events: components["schemas"]["BusinessAuditEventResponse"][];
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Events */
            total_events: number;
            /** Total Pages */
            total_pages: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RecentBusinessAuditResponse
         * @description At most four events for Head Coach dashboard activity.
         */
        RecentBusinessAuditResponse: {
            /** Events */
            events: components["schemas"]["BusinessAuditEventResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_business_audit_log_api_v1_audit_log_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                actor_user_id?: string | null;
                action_category?: components["schemas"]["AuditActionCategory"] | null;
                action_type?: components["schemas"]["AuditActionType"] | null;
                entity_type?: components["schemas"]["AuditEntityType"] | null;
                target_entity_id?: string | null;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessAuditPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_business_audit_actor_options_api_v1_audit_log_actors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessAuditActorOptionsResponse"];
                };
            };
        };
    };
    get_recent_business_activity_api_v1_audit_log_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentBusinessAuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
