/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Quality
         * @description Return one bounded findings page without creating an audit event.
         */
        get: operations["get_data_quality_api_v1_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-quality/remediations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Data Quality Remediation
         * @description Apply one exact correction through its normal domain transaction.
         */
        post: operations["apply_data_quality_remediation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgeGroup
         * @description Supported cricket team age groups.
         * @enum {string}
         */
        AgeGroup: "J" | "U11" | "U13" | "U15";
        /**
         * AuditActionCategory
         * @description Business domains represented in the academy activity history.
         * @enum {string}
         */
        AuditActionCategory: "coach" | "player" | "team" | "roster" | "calendar";
        /**
         * AuditActionType
         * @description Stable identifiers for the initial business-audit action catalogue.
         * @enum {string}
         */
        AuditActionType: "coach.created" | "coach.activated" | "coach.deactivated" | "coach.team_assignments_updated" | "player.created" | "player.updated" | "team.created" | "team.updated" | "roster.added" | "roster.removed" | "roster.reordered" | "calendar.standalone_created" | "calendar.standalone_updated" | "calendar.standalone_deleted" | "calendar.series_created" | "calendar.series_updated" | "calendar.series_deleted" | "calendar.occurrence_updated" | "calendar.occurrence_moved" | "calendar.occurrence_deleted";
        /**
         * AuditEntityType
         * @description Historical target kinds supported by the business-audit feed.
         * @enum {string}
         */
        AuditEntityType: "coach" | "player" | "team" | "roster" | "calendar_event" | "recurrence_series";
        /**
         * AuditLogResponse
         * @description Public audit metadata available to authenticated head coaches.
         */
        AuditLogResponse: {
            /**
             * Event Timestamp
             * Format: date-time
             */
            event_timestamp: string;
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ip Address */
            ip_address: string | null;
            /** Reason */
            reason: string | null;
            /** Result */
            result: string;
            /** Session Id */
            session_id: string | null;
            /** Target Resource */
            target_resource: string | null;
            /** User Agent */
            user_agent: string | null;
            /** User Id */
            user_id: string | null;
        };
        /**
         * BatchPerformanceRequest
         * @description Atomic batch of one to 30 player performances.
         *
         *     The upper bound covers two complete 15-player academy rosters while keeping
         *     parsing, database writes, and aggregate recalculation bounded.
         */
        BatchPerformanceRequest: {
            /** Performances */
            performances: components["schemas"]["PlayerPerformance"][];
        };
        /**
         * BatchPerformanceResponse
         * @description Counts produced by a successful atomic batch submission.
         */
        BatchPerformanceResponse: {
            /** Batting Records */
            batting_records: number;
            /** Bowling Records */
            bowling_records: number;
            /** Fielding Records */
            fielding_records: number;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Performances Created */
            performances_created: number;
            /** Players Stats Updated */
            players_stats_updated: number;
        };
        /**
         * BattingPerformance
         * @description Optional batting metrics for one player in one match.
         */
        BattingPerformance: {
            /**
             * Balls Faced
             * @default 0
             */
            balls_faced: number;
            /** @default not out */
            dismissal: components["schemas"]["DismissalType"];
            /**
             * Fours
             * @default 0
             */
            fours: number;
            /** Notes */
            notes?: string | null;
            /**
             * Runs Scored
             * @default 0
             */
            runs_scored: number;
            /**
             * Sixes
             * @default 0
             */
            sixes: number;
        };
        /**
         * BattingStatsResponse
         * @description Lifetime batting totals for one match format.
         */
        BattingStatsResponse: {
            /** Balls Faced */
            balls_faced: number;
            /** Ducks */
            ducks: number;
            /** Fifties */
            fifties: number;
            format: components["schemas"]["MatchFormat"];
            /** Fours */
            fours: number;
            /** High Score */
            high_score: number;
            /** Hundreds */
            hundreds: number;
            /** Innings */
            innings: number;
            /** Matches */
            matches: number;
            /** Not Outs */
            not_outs: number;
            /** Runs */
            runs: number;
            /** Sixes */
            sixes: number;
        };
        /**
         * BattingStyle
         * @description Supported batting orientations.
         * @enum {string}
         */
        BattingStyle: "right" | "left";
        /**
         * BowlingPerformance
         * @description Optional bowling metrics for one player in one match.
         */
        BowlingPerformance: {
            /**
             * Maidens
             * @default 0
             */
            maidens: number;
            /** Notes */
            notes?: string | null;
            /**
             * Overs Bowled
             * @default 0.0
             */
            overs_bowled: number | string;
            /**
             * Runs Conceded
             * @default 0
             */
            runs_conceded: number;
            /**
             * Wickets Taken
             * @default 0
             */
            wickets_taken: number;
            /**
             * Wides
             * @default 0
             */
            wides: number;
        };
        /**
         * BowlingStatsResponse
         * @description Lifetime bowling totals for one match format.
         */
        BowlingStatsResponse: {
            /** Best Bowled */
            best_bowled: string | null;
            /** Catches */
            catches: number;
            /** Five Wicket Hauls */
            five_wicket_hauls: number;
            format: components["schemas"]["MatchFormat"];
            /** Four Wicket Hauls */
            four_wicket_hauls: number;
            /** Innings */
            innings: number;
            /** Maidens */
            maidens: number;
            /** Matches */
            matches: number;
            /** Overs Bowled */
            overs_bowled: number;
            /** Runs Conceded */
            runs_conceded: number;
            /** Wickets */
            wickets: number;
            /** Wides */
            wides: number;
        };
        /**
         * BowlingStyle
         * @description Supported bowling styles.
         * @enum {string}
         */
        BowlingStyle: "right-arm fast" | "right-arm medium" | "right-arm off-break" | "right-arm leg-break" | "left-arm fast" | "left-arm medium" | "left-arm orthodox" | "left-arm unorthodox";
        /**
         * BusinessAuditActorOption
         * @description One historical actor snapshot available as a bounded filter option.
         */
        BusinessAuditActorOption: {
            /** Actor Display Name */
            actor_display_name: string;
            /** Actor Role */
            actor_role: string | null;
            /**
             * Actor User Id
             * Format: uuid
             */
            actor_user_id: string;
        };
        /**
         * BusinessAuditActorOptionsResponse
         * @description At most 100 distinct actor snapshots.
         */
        BusinessAuditActorOptionsResponse: {
            /** Actors */
            actors: components["schemas"]["BusinessAuditActorOption"][];
        };
        /**
         * BusinessAuditEventResponse
         * @description Stored snapshots and allowlisted detail exposed by the API.
         */
        BusinessAuditEventResponse: {
            action_category: components["schemas"]["AuditActionCategory"];
            action_type: components["schemas"]["AuditActionType"];
            /** Actor Display Name */
            actor_display_name: string | null;
            /** Actor Role */
            actor_role: string | null;
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["BusinessAuditMetadataValue"];
            };
            /** Request Id */
            request_id: string | null;
            /** Summary */
            summary: string;
            /** Target Entity Id */
            target_entity_id: string | null;
            target_entity_type: components["schemas"]["AuditEntityType"];
            /** Target Label */
            target_label: string | null;
        };
        BusinessAuditMetadataScalar: string | number | boolean | null;
        BusinessAuditMetadataValue: components["schemas"]["BusinessAuditMetadataScalar"] | components["schemas"]["BusinessAuditMetadataScalar"][];
        /**
         * BusinessAuditPageResponse
         * @description One stable server-paginated business-audit page.
         */
        BusinessAuditPageResponse: {
            /** Events */
            events: components["schemas"]["BusinessAuditEventResponse"][];
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Events */
            total_events: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * CalendarEventCreate
         * @description Payload for atomically creating a standalone event or series.
         */
        CalendarEventCreate: {
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            recurrence?: components["schemas"]["CalendarRecurrence"] | null;
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
        };
        /**
         * CalendarEventDefinitionResponse
         * @description Persisted event definition returned after successful mutation.
         */
        CalendarEventDefinitionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            recurrence?: components["schemas"]["RecurrenceSeriesResponse"] | null;
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarEventDelete
         * @description Canonical owning-event version required for hard deletion.
         */
        CalendarEventDelete: {
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarEventInstance
         * @description An effective standalone or calculated recurring event instance.
         */
        CalendarEventInstance: {
            /** Age Groups */
            age_groups: components["schemas"]["AgeGroup"][];
            /** End Time */
            end_time: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            event_type: components["schemas"]["EventType"];
            /** Event Version Number */
            event_version_number: number;
            /** Exception Id */
            exception_id: string | null;
            /** Exception Version Number */
            exception_version_number?: number | null;
            /** Is All Day */
            is_all_day: boolean;
            /** Is Recurring */
            is_recurring: boolean;
            /** Name */
            name: string;
            /** Occurrence Id */
            occurrence_id: string;
            /**
             * Original Date
             * Format: date
             */
            original_date: string;
            /** Recurrence Summary */
            recurrence_summary: string | null;
            scope_kind: components["schemas"]["ScopeKind"];
            series_definition?: components["schemas"]["CalendarEventDefinitionResponse"] | null;
            /** Series Id */
            series_id: string | null;
            /** Start Time */
            start_time: string | null;
        };
        /**
         * CalendarOccurrenceDelete
         * @description Owning-event and existing exception versions for one deletion.
         */
        CalendarOccurrenceDelete: {
            /** Exception Version Number */
            exception_version_number?: number | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarOccurrenceUpdate
         * @description Complete occurrence snapshot and owning-event/exception versions.
         */
        CalendarOccurrenceUpdate: {
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /** Exception Version Number */
            exception_version_number?: number | null;
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarRangeResponse
         * @description Inclusive bounded range of effective calendar instances.
         */
        CalendarRangeResponse: {
            /**
             * Academy Today
             * Format: date
             */
            academy_today: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Events */
            events: components["schemas"]["CalendarEventInstance"][];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /**
         * CalendarRecurrence
         * @description A weekly or yearly fixed-interval recurrence request.
         */
        CalendarRecurrence: {
            /** End Date */
            end_date?: string | null;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** Occurrence Count */
            occurrence_count?: number | null;
            termination: components["schemas"]["RecurrenceTermination"];
        };
        /**
         * CalendarScope
         * @description An unambiguous academy-wide or age-group event audience.
         */
        CalendarScope: {
            /** Age Groups */
            age_groups?: components["schemas"]["AgeGroup"][];
            scope_kind: components["schemas"]["ScopeKind"];
        };
        /**
         * CalendarSeriesUpdate
         * @description Complete recurring-series replacement with impact confirmation.
         */
        CalendarSeriesUpdate: {
            /**
             * Confirm Exception Removals
             * @default false
             */
            confirm_exception_removals: boolean;
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            recurrence: components["schemas"]["CalendarRecurrence"];
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarStandaloneUpdate
         * @description Complete standalone replacement carrying its canonical OCC version.
         */
        CalendarStandaloneUpdate: {
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarTodayResponse
         * @description Academy-local current date and its effective event instances.
         */
        CalendarTodayResponse: {
            /**
             * Academy Today
             * Format: date
             */
            academy_today: string;
            /** Events */
            events: components["schemas"]["CalendarEventInstance"][];
        };
        /**
         * CoachCreate
         * @description Payload for creating an assistant coach account.
         */
        CoachCreate: {
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Team Ids */
            team_ids?: string[];
        };
        /**
         * CoachCreateResponse
         * @description Creation response containing the one-time plaintext password.
         */
        CoachCreateResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            role: components["schemas"]["UserRole"];
            /** Teams */
            teams?: components["schemas"]["CoachTeamResponse"][];
            /** Temporary Password */
            temporary_password: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * CoachResponse
         * @description Public coach account information, including current team assignments.
         */
        CoachResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            role: components["schemas"]["UserRole"];
            /** Teams */
            teams?: components["schemas"]["CoachTeamResponse"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * CoachStatusUpdate
         * @description OCC version supplied for a coach account status mutation.
         */
        CoachStatusUpdate: {
            /** Version Number */
            version_number: number;
        };
        /**
         * CoachTeamResponse
         * @description A compact team representation nested in coach responses.
         */
        CoachTeamResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * CoachTeamUpdate
         * @description Complete desired team-assignment set with an OCC version.
         */
        CoachTeamUpdate: {
            /** Team Ids */
            team_ids?: string[];
            /** Version Number */
            version_number: number;
        };
        /**
         * CurrentSessionResponse
         * @description Public metadata for the session serving the current request.
         */
        CurrentSessionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Last Used At
             * Format: date-time
             */
            last_used_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * CurrentUserResponse
         * @description Authenticated account profile plus its current session metadata.
         */
        CurrentUserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            role: components["schemas"]["UserRole"];
            session: components["schemas"]["CurrentSessionResponse"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** @enum {string} */
        DataQualityAuditAction: "roster.reordered" | "roster.removed" | "coach.team_assignments_updated";
        /**
         * DataQualityFinding
         * @description One non-persisted violation of a registered quality rule.
         */
        DataQualityFinding: {
            direct_remediation: components["schemas"]["DirectQualityRemediation"] | null;
            domain: components["schemas"]["QualityDomain"];
            /** Entity Id */
            entity_id: string | null;
            /** Entity Label */
            entity_label: string;
            entity_type: components["schemas"]["QualityEntityType"];
            /** Explanation */
            explanation: string;
            /** Finding Id */
            finding_id: string;
            /** Recommended Action */
            recommended_action: string;
            /** Related Entities */
            related_entities: components["schemas"]["RelatedQualityEntity"][];
            rule_id: components["schemas"]["QualityRuleId"];
            severity: components["schemas"]["QualitySeverity"];
            /** Title */
            title: string;
        };
        /**
         * DataQualityPageResponse
         * @description One deterministic and bounded current-state findings page.
         */
        DataQualityPageResponse: {
            /** Findings */
            findings: components["schemas"]["DataQualityFinding"][];
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            summary: components["schemas"]["DataQualitySummary"];
            /** Total Findings */
            total_findings: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * DataQualityRemediationResult
         * @description User-safe result for one successfully applied domain mutation.
         */
        DataQualityRemediationResult: {
            action: components["schemas"]["QualityAction"];
            /**
             * Affected Entity Id
             * Format: uuid
             */
            affected_entity_id: string;
            audit_action: components["schemas"]["DataQualityAuditAction"];
            /** Message */
            message: string;
            /**
             * Status
             * @default applied
             * @constant
             */
            status: "applied";
        };
        /**
         * DataQualitySummary
         * @description Unfiltered counts calculated from the current finding set.
         */
        DataQualitySummary: {
            /** Critical Count */
            critical_count: number;
            /** Domain Counts */
            domain_counts: {
                [key: string]: number;
            };
            /** Info Count */
            info_count: number;
            /** Total Findings */
            total_findings: number;
            /** Warning Count */
            warning_count: number;
        };
        DirectQualityRemediation: components["schemas"]["NormalizeRosterOrderRemediation"] | components["schemas"]["RemoveInactivePlayerRemediation"] | components["schemas"]["RemoveInactiveAssistantAssignmentRemediation"];
        /**
         * DismissalType
         * @description Supported batting dismissal outcomes.
         * @enum {string}
         */
        DismissalType: "not out" | "caught" | "bowled" | "lbw" | "run out" | "stumped" | "other";
        /**
         * EventType
         * @description Supported academy calendar event classifications.
         * @enum {string}
         */
        EventType: "practice" | "game" | "miscellaneous";
        /**
         * FieldingPerformance
         * @description Optional fielding metrics for one player in one match.
         */
        FieldingPerformance: {
            /**
             * Catches
             * @default 0
             */
            catches: number;
            /**
             * Dropped Catches
             * @default 0
             */
            dropped_catches: number;
            /** Notes */
            notes?: string | null;
            /**
             * Run Outs
             * @default 0
             */
            run_outs: number;
            /**
             * Stumpings
             * @default 0
             */
            stumpings: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Email and plaintext password credentials supplied during login.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MatchCreate
         * @description Payload for recording a cricket match.
         */
        MatchCreate: {
            format: components["schemas"]["MatchFormat"];
            /**
             * Match Date
             * Format: date
             */
            match_date: string;
            /** Opponent Name */
            opponent_name: string;
            /** Result */
            result: string;
            /** Venue */
            venue: string;
        };
        /**
         * MatchFormat
         * @description Supported cricket match formats.
         * @enum {string}
         */
        MatchFormat: "T20" | "one-day" | "test" | "other";
        /**
         * MatchResponse
         * @description Complete server-managed match representation.
         */
        MatchResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            format: components["schemas"]["MatchFormat"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Date
             * Format: date
             */
            match_date: string;
            /** Opponent Name */
            opponent_name: string;
            /** Result */
            result: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Venue */
            venue: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * NormalizeRosterOrderRemediation
         * @description Current target metadata for a safe roster-order normalization.
         */
        NormalizeRosterOrderRemediation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "normalize_roster_order";
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /** Expected Team Version */
            expected_team_version: number;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * NormalizeRosterOrderRequest
         * @description Confirmation-gated command for one team's current roster order.
         */
        NormalizeRosterOrderRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "normalize_roster_order";
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Expected Team Version */
            expected_team_version: number;
            /** Finding Id */
            finding_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * PaginatedCoachResponse
         * @description Server-paginated coach collection metadata.
         */
        PaginatedCoachResponse: {
            /** Coaches */
            coaches: components["schemas"]["CoachResponse"][];
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Coaches */
            total_coaches: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PaginatedPlayerResponse
         * @description One page of active players with navigation metadata.
         */
        PaginatedPlayerResponse: {
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Players */
            players: components["schemas"]["PlayerResponse"][];
            /** Total Pages */
            total_pages: number;
            /** Total Players */
            total_players: number;
        };
        /**
         * PaginatedTeamResponse
         * @description A stable, server-paginated page of team summaries.
         */
        PaginatedTeamResponse: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Teams */
            teams: components["schemas"]["TeamResponse"][];
            /** Total Pages */
            total_pages: number;
            /** Total Teams */
            total_teams: number;
        };
        /**
         * PlayerCreate
         * @description Payload for creating a player profile.
         */
        PlayerCreate: {
            batting_style: components["schemas"]["BattingStyle"];
            /** Bio */
            bio?: string | null;
            bowling_style: components["schemas"]["BowlingStyle"];
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Player Metadata */
            player_metadata?: {
                [key: string]: unknown;
            };
            player_type: components["schemas"]["PlayerType"];
        };
        /**
         * PlayerPerformance
         * @description All supplied performance groups for one player.
         */
        PlayerPerformance: {
            batting?: components["schemas"]["BattingPerformance"] | null;
            bowling?: components["schemas"]["BowlingPerformance"] | null;
            fielding?: components["schemas"]["FieldingPerformance"] | null;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
        };
        /**
         * PlayerResponse
         * @description Complete server-managed player representation.
         */
        PlayerResponse: {
            batting_style: components["schemas"]["BattingStyle"];
            /** Bio */
            bio: string | null;
            bowling_style: components["schemas"]["BowlingStyle"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            /** Player Metadata */
            player_metadata: {
                [key: string]: unknown;
            };
            player_type: components["schemas"]["PlayerType"];
            /** Teams */
            teams?: components["schemas"]["TeamSummary"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * PlayerType
         * @description Supported player roles.
         * @enum {string}
         */
        PlayerType: "batter" | "bowler" | "all-rounder" | "wicket-keeper";
        /**
         * PlayerUpdate
         * @description Partial player update carrying the required OCC version.
         */
        PlayerUpdate: {
            batting_style?: components["schemas"]["BattingStyle"] | null;
            /** Bio */
            bio?: string | null;
            bowling_style?: components["schemas"]["BowlingStyle"] | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Last Name */
            last_name?: string | null;
            /** Player Metadata */
            player_metadata?: {
                [key: string]: unknown;
            } | null;
            player_type?: components["schemas"]["PlayerType"] | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * ProfileUpdate
         * @description Editable profile fields supplied by an authenticated user.
         */
        ProfileUpdate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /**
         * QualityAction
         * @description Direct corrections supported by the initial quality contract.
         * @enum {string}
         */
        QualityAction: "normalize_roster_order" | "remove_inactive_player" | "remove_inactive_assistant_assignment";
        /**
         * QualityDomain
         * @description Allowlisted academy domains evaluated by Data Quality.
         * @enum {string}
         */
        QualityDomain: "players" | "teams" | "rosters" | "coaches" | "calendar";
        /**
         * QualityEntityType
         * @description Entity labels permitted in current-state quality findings.
         * @enum {string}
         */
        QualityEntityType: "player" | "team" | "roster" | "roster_membership" | "coach" | "coach_assignment" | "calendar_event" | "recurrence_series" | "occurrence_exception" | "academy";
        /**
         * QualityRuleId
         * @description Stable identifiers for the initial Data Quality rule catalogue.
         * @enum {string}
         */
        QualityRuleId: "player.active_unassigned" | "player.inactive_rostered" | "player.normalized_identity_duplicate" | "team.roster_below_minimum" | "team.roster_above_maximum" | "roster.order_non_positive" | "roster.order_duplicate" | "roster.order_gap" | "roster.order_non_contiguous" | "team.normalized_name_conflict" | "team.no_assigned_coach" | "coach.sole_head_coach_integrity" | "coach.inactive_assigned" | "coach.active_assistant_unassigned" | "coach.assignment_invalid_role" | "calendar.recurrence_end_before_start" | "calendar.stale_occurrence_exception";
        /**
         * QualitySeverity
         * @description Operational impact levels exposed by Data Quality findings.
         * @enum {string}
         */
        QualitySeverity: "critical" | "warning" | "info";
        /**
         * RecentBusinessAuditResponse
         * @description At most four events for Head Coach dashboard activity.
         */
        RecentBusinessAuditResponse: {
            /** Events */
            events: components["schemas"]["BusinessAuditEventResponse"][];
        };
        /**
         * RecurrenceFrequency
         * @description Supported fixed-interval calendar recurrence frequencies.
         * @enum {string}
         */
        RecurrenceFrequency: "weekly" | "yearly";
        /**
         * RecurrenceSeriesResponse
         * @description Persisted recurrence identity and derived rule fields.
         */
        RecurrenceSeriesResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** End Date */
            end_date: string | null;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Month */
            month?: number | null;
            /** Month Day */
            month_day?: number | null;
            /** Occurrence Count */
            occurrence_count?: number | null;
            termination: components["schemas"]["RecurrenceTermination"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weekday */
            weekday?: number | null;
        };
        /**
         * RecurrenceTermination
         * @description Supported ways to terminate a recurring calendar series.
         * @enum {string}
         */
        RecurrenceTermination: "never" | "end_date" | "occurrence_count";
        /**
         * RelatedQualityEntity
         * @description A deterministic related record needed to explain one finding.
         */
        RelatedQualityEntity: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            entity_type: components["schemas"]["QualityEntityType"];
        };
        /**
         * RemoveInactiveAssistantAssignmentRemediation
         * @description Current target metadata for removing one Assistant assignment.
         */
        RemoveInactiveAssistantAssignmentRemediation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_assistant_assignment";
            /**
             * Coach Id
             * Format: uuid
             */
            coach_id: string;
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /** Expected Coach Version */
            expected_coach_version: number;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RemoveInactiveAssistantAssignmentRequest
         * @description Confirmation-gated command for one inactive Assistant assignment.
         */
        RemoveInactiveAssistantAssignmentRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_assistant_assignment";
            /**
             * Coach Id
             * Format: uuid
             */
            coach_id: string;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Expected Coach Version */
            expected_coach_version: number;
            /** Finding Id */
            finding_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RemoveInactivePlayerRemediation
         * @description Current target metadata for removing one inactive membership.
         */
        RemoveInactivePlayerRemediation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_player";
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /** Expected Team Version */
            expected_team_version: number;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RemoveInactivePlayerRequest
         * @description Confirmation-gated command for exactly one inactive membership.
         */
        RemoveInactivePlayerRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_player";
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Expected Team Version */
            expected_team_version: number;
            /** Finding Id */
            finding_id: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * ScopeKind
         * @description Supported audience scope representations for calendar events.
         * @enum {string}
         */
        ScopeKind: "age_group" | "all_academy";
        /**
         * TeamCreate
         * @description Validated payload for creating a complete team roster.
         */
        TeamCreate: {
            age_group: components["schemas"]["AgeGroup"];
            /** Name */
            name: string;
            /** Player Ids */
            player_ids: string[];
        };
        /**
         * TeamPlayerResponse
         * @description Legacy public representation of a single team membership.
         */
        TeamPlayerResponse: {
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * TeamResponse
         * @description Team summary used in lists and mutation responses.
         */
        TeamResponse: {
            age_group: components["schemas"]["AgeGroup"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Player Count
             * @default 0
             */
            player_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * TeamRosterPlayerResponse
         * @description A roster entry, including inactive historical members.
         */
        TeamRosterPlayerResponse: {
            /** First Name */
            first_name: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /** Roster Order */
            roster_order: number;
        };
        /**
         * TeamRosterResponse
         * @description Ordered players belonging to one team.
         */
        TeamRosterResponse: {
            /** Players */
            players: components["schemas"]["TeamRosterPlayerResponse"][];
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * TeamSummary
         * @description Lightweight team identity embedded in player responses.
         */
        TeamSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * TeamUpdate
         * @description Complete replacement payload carrying the OCC version.
         */
        TeamUpdate: {
            age_group: components["schemas"]["AgeGroup"];
            /** Name */
            name: string;
            /** Player Ids */
            player_ids: string[];
            /** Version Number */
            version_number: number;
        };
        /**
         * TokenResponse
         * @description Bearer access token returned after login or refresh.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /**
         * UserCreate
         * @description Payload for creating a user account.
         */
        UserCreate: {
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Password */
            password: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserPasswordChange
         * @description Payload for replacing an account password.
         */
        UserPasswordChange: {
            /** New Password */
            new_password: string;
        };
        /**
         * UserResponse
         * @description Public account representation, intentionally excluding the password hash.
         */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            role: components["schemas"]["UserRole"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * UserRole
         * @description Supported user account roles.
         * @enum {string}
         */
        UserRole: "head coach" | "assistant coach" | "player";
        /**
         * UserRoleUpdate
         * @description Payload for a head coach changing an account's role.
         */
        UserRoleUpdate: {
            role: components["schemas"]["UserRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_data_quality_api_v1_data_quality_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                severity?: components["schemas"]["QualitySeverity"] | null;
                domain?: components["schemas"]["QualityDomain"] | null;
                rule_id?: components["schemas"]["QualityRuleId"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_data_quality_remediation: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NormalizeRosterOrderRequest"] | components["schemas"]["RemoveInactivePlayerRequest"] | components["schemas"]["RemoveInactiveAssistantAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityRemediationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
