/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Quality */
        get: operations["get_data_quality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-quality/remediations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Data Quality Remediation */
        post: operations["apply_data_quality_remediation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DataQualityAuditAction: "roster.reordered" | "roster.removed" | "coach.team_assignments_updated";
        /**
         * DataQualityFinding
         * @description One non-persisted violation of a registered quality rule.
         */
        DataQualityFinding: {
            direct_remediation: components["schemas"]["DirectQualityRemediation"] | null;
            domain: components["schemas"]["QualityDomain"];
            /** Entity Id */
            entity_id: string | null;
            /** Entity Label */
            entity_label: string;
            entity_type: components["schemas"]["QualityEntityType"];
            /** Explanation */
            explanation: string;
            /** Finding Id */
            finding_id: string;
            /** Recommended Action */
            recommended_action: string;
            /** Related Entities */
            related_entities: components["schemas"]["RelatedQualityEntity"][];
            rule_id: components["schemas"]["QualityRuleId"];
            severity: components["schemas"]["QualitySeverity"];
            /** Title */
            title: string;
        };
        /**
         * DataQualityPageResponse
         * @description One deterministic and bounded current-state findings page.
         */
        DataQualityPageResponse: {
            /** Findings */
            findings: components["schemas"]["DataQualityFinding"][];
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            summary: components["schemas"]["DataQualitySummary"];
            /** Total Findings */
            total_findings: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * DataQualityRemediationResult
         * @description User-safe result for one successfully applied domain mutation.
         */
        DataQualityRemediationResult: {
            action: components["schemas"]["QualityAction"];
            /**
             * Affected Entity Id
             * Format: uuid
             */
            affected_entity_id: string;
            audit_action: components["schemas"]["DataQualityAuditAction"];
            /** Message */
            message: string;
            /**
             * Status
             * @default applied
             * @constant
             */
            status: "applied";
        };
        /**
         * DataQualitySummary
         * @description Unfiltered counts calculated from the current finding set.
         */
        DataQualitySummary: {
            /** Critical Count */
            critical_count: number;
            /** Domain Counts */
            domain_counts: {
                [key: string]: number;
            };
            /** Info Count */
            info_count: number;
            /** Total Findings */
            total_findings: number;
            /** Warning Count */
            warning_count: number;
        };
        DirectQualityRemediation: components["schemas"]["NormalizeRosterOrderRemediation"] | components["schemas"]["RemoveInactivePlayerRemediation"] | components["schemas"]["RemoveInactiveAssistantAssignmentRemediation"];
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NormalizeRosterOrderRemediation
         * @description Current target metadata for a safe roster-order normalization.
         */
        NormalizeRosterOrderRemediation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "normalize_roster_order";
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /** Expected Team Version */
            expected_team_version: number;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * NormalizeRosterOrderRequest
         * @description Confirmation-gated command for one team's current roster order.
         */
        NormalizeRosterOrderRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "normalize_roster_order";
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
            /** Expected Team Version */
            expected_team_version: number;
            /** Finding Id */
            finding_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * QualityAction
         * @description Direct corrections supported by the initial quality contract.
         * @enum {string}
         */
        QualityAction: "normalize_roster_order" | "remove_inactive_player" | "remove_inactive_assistant_assignment";
        /**
         * QualityDomain
         * @description Allowlisted academy domains evaluated by Data Quality.
         * @enum {string}
         */
        QualityDomain: "players" | "teams" | "rosters" | "coaches" | "calendar";
        /**
         * QualityEntityType
         * @description Entity labels permitted in current-state quality findings.
         * @enum {string}
         */
        QualityEntityType: "player" | "team" | "roster" | "roster_membership" | "coach" | "coach_assignment" | "calendar_event" | "recurrence_series" | "occurrence_exception" | "academy";
        /**
         * QualityRuleId
         * @description Stable identifiers for the initial Data Quality rule catalogue.
         * @enum {string}
         */
        QualityRuleId: "player.active_unassigned" | "player.inactive_rostered" | "player.normalized_identity_duplicate" | "team.roster_below_minimum" | "team.roster_above_maximum" | "roster.order_non_positive" | "roster.order_duplicate" | "roster.order_gap" | "roster.order_non_contiguous" | "team.normalized_name_conflict" | "team.no_assigned_coach" | "coach.sole_head_coach_integrity" | "coach.inactive_assigned" | "coach.active_assistant_unassigned" | "coach.assignment_invalid_role" | "calendar.recurrence_end_before_start" | "calendar.stale_occurrence_exception";
        /**
         * QualitySeverity
         * @description Operational impact levels exposed by Data Quality findings.
         * @enum {string}
         */
        QualitySeverity: "critical" | "warning" | "info";
        /**
         * RelatedQualityEntity
         * @description A deterministic related record needed to explain one finding.
         */
        RelatedQualityEntity: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            entity_type: components["schemas"]["QualityEntityType"];
        };
        /**
         * RemoveInactiveAssistantAssignmentRemediation
         * @description Current target metadata for removing one Assistant assignment.
         */
        RemoveInactiveAssistantAssignmentRemediation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_assistant_assignment";
            /**
             * Coach Id
             * Format: uuid
             */
            coach_id: string;
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /** Expected Coach Version */
            expected_coach_version: number;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RemoveInactiveAssistantAssignmentRequest
         * @description Confirmation-gated command for one inactive Assistant assignment.
         */
        RemoveInactiveAssistantAssignmentRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_assistant_assignment";
            /**
             * Coach Id
             * Format: uuid
             */
            coach_id: string;
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
            /** Expected Coach Version */
            expected_coach_version: number;
            /** Finding Id */
            finding_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RemoveInactivePlayerRemediation
         * @description Current target metadata for removing one inactive membership.
         */
        RemoveInactivePlayerRemediation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_player";
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /** Expected Team Version */
            expected_team_version: number;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RemoveInactivePlayerRequest
         * @description Confirmation-gated command for exactly one inactive membership.
         */
        RemoveInactivePlayerRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_player";
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
            /** Expected Team Version */
            expected_team_version: number;
            /** Finding Id */
            finding_id: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_data_quality: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                severity?: components["schemas"]["QualitySeverity"] | null;
                domain?: components["schemas"]["QualityDomain"] | null;
                rule_id?: components["schemas"]["QualityRuleId"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_data_quality_remediation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NormalizeRosterOrderRequest"] | components["schemas"]["RemoveInactivePlayerRequest"] | components["schemas"]["RemoveInactiveAssistantAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityRemediationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
