/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Quality
         * @description Return one bounded findings page without creating an audit event.
         */
        get: operations["get_data_quality_api_v1_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-quality/remediations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Data Quality Remediation
         * @description Apply one exact correction through its normal domain transaction.
         */
        post: operations["apply_data_quality_remediation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgeGroup
         * @description Supported cricket team age groups.
         * @enum {string}
         */
        AgeGroup: "J" | "U11" | "U13" | "U15";
        /**
         * AuditActionCategory
         * @description Business domains represented in the academy activity history.
         * @enum {string}
         */
        AuditActionCategory: "coach" | "player" | "team" | "roster" | "calendar" | "scoring";
        /**
         * AuditActionType
         * @description Stable identifiers for the initial business-audit action catalogue.
         * @enum {string}
         */
        AuditActionType: "coach.created" | "coach.activated" | "coach.deactivated" | "coach.team_assignments_updated" | "player.created" | "player.updated" | "player.account_linked" | "player.account_unlinked" | "player.account_reassigned" | "team.created" | "team.updated" | "roster.added" | "roster.removed" | "roster.reordered" | "calendar.standalone_created" | "calendar.standalone_updated" | "calendar.standalone_deleted" | "calendar.series_created" | "calendar.series_updated" | "calendar.series_deleted" | "calendar.occurrence_updated" | "calendar.occurrence_moved" | "calendar.occurrence_deleted" | "scoring.initialized";
        /**
         * AuditEntityType
         * @description Historical target kinds supported by the business-audit feed.
         * @enum {string}
         */
        AuditEntityType: "coach" | "player" | "team" | "roster" | "calendar_event" | "recurrence_series" | "match";
        /**
         * AuditLogResponse
         * @description Public audit metadata available to authenticated head coaches.
         */
        AuditLogResponse: {
            /**
             * Event Timestamp
             * Format: date-time
             */
            event_timestamp: string;
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ip Address */
            ip_address: string | null;
            /** Reason */
            reason: string | null;
            /** Result */
            result: string;
            /** Session Id */
            session_id: string | null;
            /** Target Resource */
            target_resource: string | null;
            /** User Agent */
            user_agent: string | null;
            /** User Id */
            user_id: string | null;
        };
        /**
         * BatchPerformanceRequest
         * @description Atomic batch of one to 30 player performances.
         *
         *     The upper bound covers two complete 15-player academy rosters while keeping
         *     parsing, database writes, and aggregate recalculation bounded.
         */
        BatchPerformanceRequest: {
            /** Performances */
            performances: components["schemas"]["PlayerPerformance"][];
        };
        /**
         * BatchPerformanceResponse
         * @description Counts produced by a successful atomic batch submission.
         */
        BatchPerformanceResponse: {
            /** Batting Records */
            batting_records: number;
            /** Bowling Records */
            bowling_records: number;
            /** Fielding Records */
            fielding_records: number;
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Performances Created */
            performances_created: number;
            /** Players Stats Updated */
            players_stats_updated: number;
        };
        /**
         * BattingPerformance
         * @description Optional batting metrics for one player in one match.
         */
        BattingPerformance: {
            /**
             * Balls Faced
             * @default 0
             */
            balls_faced: number;
            /** @default not out */
            dismissal: components["schemas"]["DismissalType"];
            /**
             * Fours
             * @default 0
             */
            fours: number;
            /** Notes */
            notes?: string | null;
            /**
             * Runs Scored
             * @default 0
             */
            runs_scored: number;
            /**
             * Sixes
             * @default 0
             */
            sixes: number;
        };
        /**
         * BattingStatsResponse
         * @description Lifetime batting totals for one match format.
         */
        BattingStatsResponse: {
            /** Balls Faced */
            balls_faced: number;
            /** Ducks */
            ducks: number;
            /** Fifties */
            fifties: number;
            format: components["schemas"]["MatchFormat"];
            /** Fours */
            fours: number;
            /** High Score */
            high_score: number;
            /** Hundreds */
            hundreds: number;
            /** Innings */
            innings: number;
            /** Matches */
            matches: number;
            /** Not Outs */
            not_outs: number;
            /** Runs */
            runs: number;
            /** Sixes */
            sixes: number;
        };
        /**
         * BattingStyle
         * @description Supported batting orientations.
         * @enum {string}
         */
        BattingStyle: "right" | "left";
        /**
         * BlockingReasonCode
         * @description Bounded reason codes paired with non-``none`` blocking states.
         * @enum {string}
         */
        BlockingReasonCode: "innings_not_started" | "next_batter_required" | "next_bowler_required" | "no_eligible_bowler" | "incompatible_replay" | "innings_completed" | "match_completed" | "match_abandoned";
        /**
         * BlockingStateKind
         * @description Canonical read-only scoring progression states.
         * @enum {string}
         */
        BlockingStateKind: "none" | "innings_not_started" | "awaiting_next_batter" | "awaiting_next_bowler" | "reconciliation_required" | "innings_completed" | "match_completed" | "match_abandoned";
        /**
         * BlockingStateResponse
         * @description Canonical read-only progression blocker.
         */
        BlockingStateResponse: {
            /** Is Blocked */
            is_blocked: boolean;
            kind: components["schemas"]["BlockingStateKind"];
            reason_code: components["schemas"]["BlockingReasonCode"] | null;
        };
        /**
         * BowlingPerformance
         * @description Optional bowling metrics for one player in one match.
         */
        BowlingPerformance: {
            /**
             * Maidens
             * @default 0
             */
            maidens: number;
            /** Notes */
            notes?: string | null;
            /**
             * Overs Bowled
             * @default 0.0
             */
            overs_bowled: number | string;
            /**
             * Runs Conceded
             * @default 0
             */
            runs_conceded: number;
            /**
             * Wickets Taken
             * @default 0
             */
            wickets_taken: number;
            /**
             * Wides
             * @default 0
             */
            wides: number;
        };
        /**
         * BowlingStatsResponse
         * @description Lifetime bowling totals for one match format.
         */
        BowlingStatsResponse: {
            /** Best Bowled */
            best_bowled: string | null;
            /** Catches */
            catches: number;
            /** Five Wicket Hauls */
            five_wicket_hauls: number;
            format: components["schemas"]["MatchFormat"];
            /** Four Wicket Hauls */
            four_wicket_hauls: number;
            /** Innings */
            innings: number;
            /** Maidens */
            maidens: number;
            /** Matches */
            matches: number;
            /** Overs Bowled */
            overs_bowled: number;
            /** Runs Conceded */
            runs_conceded: number;
            /** Wickets */
            wickets: number;
            /** Wides */
            wides: number;
        };
        /**
         * BowlingStyle
         * @description Supported bowling styles.
         * @enum {string}
         */
        BowlingStyle: "right-arm fast" | "right-arm medium" | "right-arm off-break" | "right-arm leg-break" | "left-arm fast" | "left-arm medium" | "left-arm orthodox" | "left-arm unorthodox";
        /**
         * BusinessAuditActorOption
         * @description One historical actor snapshot available as a bounded filter option.
         */
        BusinessAuditActorOption: {
            /** Actor Display Name */
            actor_display_name: string;
            /** Actor Role */
            actor_role: string | null;
            /**
             * Actor User Id
             * Format: uuid
             */
            actor_user_id: string;
        };
        /**
         * BusinessAuditActorOptionsResponse
         * @description At most 100 distinct actor snapshots.
         */
        BusinessAuditActorOptionsResponse: {
            /** Actors */
            actors: components["schemas"]["BusinessAuditActorOption"][];
        };
        /**
         * BusinessAuditEventResponse
         * @description Stored snapshots and allowlisted detail exposed by the API.
         */
        BusinessAuditEventResponse: {
            action_category: components["schemas"]["AuditActionCategory"];
            action_type: components["schemas"]["AuditActionType"];
            /** Actor Display Name */
            actor_display_name: string | null;
            /** Actor Role */
            actor_role: string | null;
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["BusinessAuditMetadataValue"];
            };
            /** Request Id */
            request_id: string | null;
            /** Summary */
            summary: string;
            /** Target Entity Id */
            target_entity_id: string | null;
            target_entity_type: components["schemas"]["AuditEntityType"];
            /** Target Label */
            target_label: string | null;
        };
        BusinessAuditMetadataScalar: string | number | boolean | null;
        BusinessAuditMetadataValue: components["schemas"]["BusinessAuditMetadataScalar"] | components["schemas"]["BusinessAuditMetadataScalar"][];
        /**
         * BusinessAuditPageResponse
         * @description One stable server-paginated business-audit page.
         */
        BusinessAuditPageResponse: {
            /** Events */
            events: components["schemas"]["BusinessAuditEventResponse"][];
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Events */
            total_events: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * CalendarEventCreate
         * @description Payload for atomically creating a standalone event or series.
         */
        CalendarEventCreate: {
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            recurrence?: components["schemas"]["CalendarRecurrence"] | null;
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
        };
        /**
         * CalendarEventDefinitionResponse
         * @description Persisted event definition returned after successful mutation.
         */
        CalendarEventDefinitionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            recurrence?: components["schemas"]["RecurrenceSeriesResponse"] | null;
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarEventDelete
         * @description Canonical owning-event version required for hard deletion.
         */
        CalendarEventDelete: {
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarEventInstance
         * @description An effective standalone or calculated recurring event instance.
         */
        CalendarEventInstance: {
            /** Age Groups */
            age_groups: components["schemas"]["AgeGroup"][];
            /** End Time */
            end_time: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            event_type: components["schemas"]["EventType"];
            /** Event Version Number */
            event_version_number: number;
            /** Exception Id */
            exception_id: string | null;
            /** Exception Version Number */
            exception_version_number?: number | null;
            /** Is All Day */
            is_all_day: boolean;
            /** Is Recurring */
            is_recurring: boolean;
            /** Name */
            name: string;
            /** Occurrence Id */
            occurrence_id: string;
            /**
             * Original Date
             * Format: date
             */
            original_date: string;
            /** Recurrence Summary */
            recurrence_summary: string | null;
            scope_kind: components["schemas"]["ScopeKind"];
            series_definition?: components["schemas"]["CalendarEventDefinitionResponse"] | null;
            /** Series Id */
            series_id: string | null;
            /** Start Time */
            start_time: string | null;
        };
        /**
         * CalendarOccurrenceDelete
         * @description Owning-event and existing exception versions for one deletion.
         */
        CalendarOccurrenceDelete: {
            /** Exception Version Number */
            exception_version_number?: number | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarOccurrenceUpdate
         * @description Complete occurrence snapshot and owning-event/exception versions.
         */
        CalendarOccurrenceUpdate: {
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /** Exception Version Number */
            exception_version_number?: number | null;
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarRangeResponse
         * @description Inclusive bounded range of effective calendar instances.
         */
        CalendarRangeResponse: {
            /**
             * Academy Today
             * Format: date
             */
            academy_today: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Events */
            events: components["schemas"]["CalendarEventInstance"][];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /**
         * CalendarRecurrence
         * @description A weekly or yearly fixed-interval recurrence request.
         */
        CalendarRecurrence: {
            /** End Date */
            end_date?: string | null;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** Occurrence Count */
            occurrence_count?: number | null;
            termination: components["schemas"]["RecurrenceTermination"];
        };
        /**
         * CalendarScope
         * @description An unambiguous academy-wide or age-group event audience.
         */
        CalendarScope: {
            /** Age Groups */
            age_groups?: components["schemas"]["AgeGroup"][];
            scope_kind: components["schemas"]["ScopeKind"];
        };
        /**
         * CalendarSeriesUpdate
         * @description Complete recurring-series replacement with impact confirmation.
         */
        CalendarSeriesUpdate: {
            /**
             * Confirm Exception Removals
             * @default false
             */
            confirm_exception_removals: boolean;
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            recurrence: components["schemas"]["CalendarRecurrence"];
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarStandaloneUpdate
         * @description Complete standalone replacement carrying its canonical OCC version.
         */
        CalendarStandaloneUpdate: {
            /** End Time */
            end_time?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /**
             * Is All Day
             * @default false
             */
            is_all_day: boolean;
            /** Name */
            name: string;
            scope: components["schemas"]["CalendarScope"];
            /** Start Time */
            start_time?: string | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * CalendarTodayResponse
         * @description Academy-local current date and its effective event instances.
         */
        CalendarTodayResponse: {
            /**
             * Academy Today
             * Format: date
             */
            academy_today: string;
            /** Events */
            events: components["schemas"]["CalendarEventInstance"][];
        };
        /**
         * CoachCreate
         * @description Payload for creating an assistant coach account.
         */
        CoachCreate: {
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Team Ids */
            team_ids?: string[];
        };
        /**
         * CoachCreateResponse
         * @description Creation response containing the one-time plaintext password.
         */
        CoachCreateResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            role: components["schemas"]["UserRole"];
            /** Teams */
            teams?: components["schemas"]["CoachTeamResponse"][];
            /** Temporary Password */
            temporary_password: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * CoachResponse
         * @description Public coach account information, including current team assignments.
         */
        CoachResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            role: components["schemas"]["UserRole"];
            /** Teams */
            teams?: components["schemas"]["CoachTeamResponse"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * CoachStatusUpdate
         * @description OCC version supplied for a coach account status mutation.
         */
        CoachStatusUpdate: {
            /** Version Number */
            version_number: number;
        };
        /**
         * CoachTeamResponse
         * @description A compact team representation nested in coach responses.
         */
        CoachTeamResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * CoachTeamUpdate
         * @description Complete desired team-assignment set with an OCC version.
         */
        CoachTeamUpdate: {
            /** Team Ids */
            team_ids?: string[];
            /** Version Number */
            version_number: number;
        };
        /**
         * CurrentSessionResponse
         * @description Public metadata for the session serving the current request.
         */
        CurrentSessionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Last Used At
             * Format: date-time
             */
            last_used_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * CurrentUserResponse
         * @description Authenticated account profile plus its current session metadata.
         */
        CurrentUserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            role: components["schemas"]["UserRole"];
            session: components["schemas"]["CurrentSessionResponse"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DashboardActivePlayerCount
         * @description Academy or assigned-Team active Player count.
         */
        DashboardActivePlayerCount: {
            /** Count */
            count: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "active_player_count";
            /** Team Count */
            team_count: number;
        };
        /**
         * DashboardActivityEvent
         * @description Allowlisted Business Audit snapshot for Head Coach activity.
         */
        DashboardActivityEvent: {
            action_category: components["schemas"]["AuditActionCategory"];
            action_type: components["schemas"]["AuditActionType"];
            /** Actor Display Name */
            actor_display_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Summary */
            summary: string;
            /** Target Label */
            target_label: string | null;
        };
        /**
         * DashboardCalendarEvent
         * @description Useful Calendar occurrence fields without location or venue.
         */
        DashboardCalendarEvent: {
            /** Age Groups */
            age_groups: components["schemas"]["AgeGroup"][];
            /** End Time */
            end_time: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            event_type: components["schemas"]["EventType"];
            /** Name */
            name: string;
            /** Occurrence Id */
            occurrence_id: string;
            /** Start Time */
            start_time: string | null;
        };
        /**
         * DashboardCoachReference
         * @description Permitted coach identity shown in a Player's Team context.
         */
        DashboardCoachReference: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        DashboardContext: components["schemas"]["DashboardRecentActivity"] | components["schemas"]["DashboardMyTeams"];
        /**
         * DashboardEmptySection
         * @description A dashboard section with no eligible source records.
         */
        DashboardEmptySection: {
            /** Message */
            message: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "empty";
        };
        /**
         * DashboardMatch
         * @description Date-based Match summary with expanded participant labels.
         */
        DashboardMatch: {
            format: components["schemas"]["MatchFormat"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Match Date
             * Format: date
             */
            match_date: string;
            participants: components["schemas"]["src__schemas__match__MatchParticipantResponse"];
        };
        /**
         * DashboardMyTeams
         * @description Bounded role-scoped Team context.
         */
        DashboardMyTeams: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "my_teams";
            /** Teams */
            teams: components["schemas"]["DashboardTeam"][];
            /**
             * View All Path
             * @default /teams
             * @constant
             */
            view_all_path: "/teams";
        };
        DashboardPlayerSlot: components["schemas"]["DashboardActivePlayerCount"] | components["schemas"]["DashboardPlayerTeams"];
        /**
         * DashboardPlayerTeams
         * @description Concise Player summary for one or more current memberships.
         */
        DashboardPlayerTeams: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "player_teams";
            /** Team Count */
            team_count: number;
            /** Team Names */
            team_names: string[];
        };
        /** DashboardReadySection[DashboardCalendarEvent] */
        DashboardReadySection_DashboardCalendarEvent_: {
            data: components["schemas"]["DashboardCalendarEvent"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ready";
        };
        /** DashboardReadySection[DashboardContext] */
        DashboardReadySection_DashboardContext_: {
            data: components["schemas"]["DashboardContext"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ready";
        };
        /** DashboardReadySection[DashboardMatch] */
        DashboardReadySection_DashboardMatch_: {
            data: components["schemas"]["DashboardMatch"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ready";
        };
        /** DashboardReadySection[DashboardPlayerSlot] */
        DashboardReadySection_DashboardPlayerSlot_: {
            data: components["schemas"]["DashboardPlayerSlot"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ready";
        };
        /** DashboardReadySection[DashboardUpcomingEventList] */
        DashboardReadySection_DashboardUpcomingEventList_: {
            data: components["schemas"]["DashboardUpcomingEventList"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ready";
        };
        /**
         * DashboardRecentActivity
         * @description Bounded Head Coach-only context panel data.
         */
        DashboardRecentActivity: {
            /** Events */
            events: components["schemas"]["DashboardActivityEvent"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "recent_activity";
            /**
             * View All Path
             * @default /audit-log
             * @constant
             */
            view_all_path: "/audit-log";
        };
        /**
         * DashboardResponse
         * @description One bounded, server-authorized dashboard briefing.
         */
        DashboardResponse: {
            context: components["schemas"]["DashboardSection_DashboardContext_"];
            /**
             * Dashboard State
             * @enum {string}
             */
            dashboard_state: "ready" | "unlinked";
            summary: components["schemas"]["DashboardSummary"];
            upcoming_events: components["schemas"]["DashboardSection_DashboardUpcomingEventList_"];
            user: components["schemas"]["DashboardUser"];
        };
        DashboardSection_DashboardCalendarEvent_: components["schemas"]["DashboardReadySection_DashboardCalendarEvent_"] | components["schemas"]["DashboardEmptySection"] | components["schemas"]["DashboardUnlinkedSection"] | components["schemas"]["DashboardUnavailableSection"];
        DashboardSection_DashboardContext_: components["schemas"]["DashboardReadySection_DashboardContext_"] | components["schemas"]["DashboardEmptySection"] | components["schemas"]["DashboardUnlinkedSection"] | components["schemas"]["DashboardUnavailableSection"];
        DashboardSection_DashboardMatch_: components["schemas"]["DashboardReadySection_DashboardMatch_"] | components["schemas"]["DashboardEmptySection"] | components["schemas"]["DashboardUnlinkedSection"] | components["schemas"]["DashboardUnavailableSection"];
        DashboardSection_DashboardPlayerSlot_: components["schemas"]["DashboardReadySection_DashboardPlayerSlot_"] | components["schemas"]["DashboardEmptySection"] | components["schemas"]["DashboardUnlinkedSection"] | components["schemas"]["DashboardUnavailableSection"];
        DashboardSection_DashboardUpcomingEventList_: components["schemas"]["DashboardReadySection_DashboardUpcomingEventList_"] | components["schemas"]["DashboardEmptySection"] | components["schemas"]["DashboardUnlinkedSection"] | components["schemas"]["DashboardUnavailableSection"];
        /**
         * DashboardSummary
         * @description The three stable summary slots on the shared surface.
         */
        DashboardSummary: {
            next_match: components["schemas"]["DashboardSection_DashboardMatch_"];
            player_slot: components["schemas"]["DashboardSection_DashboardPlayerSlot_"];
            training: components["schemas"]["DashboardSection_DashboardCalendarEvent_"];
        };
        /**
         * DashboardTeam
         * @description One scoped Team row in an Assistant Coach or Player panel.
         */
        DashboardTeam: {
            /** Active Player Count */
            active_player_count: number;
            age_group: components["schemas"]["AgeGroup"];
            /** Coaches */
            coaches?: components["schemas"]["DashboardCoachReference"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            next_event: components["schemas"]["DashboardCalendarEvent"] | null;
        };
        /**
         * DashboardUnavailableSection
         * @description An independently failed section with explicit retry behavior.
         */
        DashboardUnavailableSection: {
            /** Message */
            message: string;
            /**
             * Retryable
             * @default true
             */
            retryable: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "unavailable";
        };
        /**
         * DashboardUnlinkedSection
         * @description A Player section withheld until an explicit profile link exists.
         */
        DashboardUnlinkedSection: {
            /** Message */
            message: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "unlinked";
        };
        DashboardUpcomingEventList: components["schemas"]["DashboardCalendarEvent"][];
        /**
         * DashboardUser
         * @description Authenticated account identity displayed in the briefing.
         */
        DashboardUser: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["UserRole"];
        };
        /** @enum {string} */
        DataQualityAuditAction: "roster.reordered" | "roster.removed" | "coach.team_assignments_updated";
        /**
         * DataQualityFinding
         * @description One non-persisted violation of a registered quality rule.
         */
        DataQualityFinding: {
            direct_remediation: components["schemas"]["DirectQualityRemediation"] | null;
            domain: components["schemas"]["QualityDomain"];
            /** Entity Id */
            entity_id: string | null;
            /** Entity Label */
            entity_label: string;
            entity_type: components["schemas"]["QualityEntityType"];
            /** Explanation */
            explanation: string;
            /** Finding Id */
            finding_id: string;
            /** Recommended Action */
            recommended_action: string;
            /** Related Entities */
            related_entities: components["schemas"]["RelatedQualityEntity"][];
            rule_id: components["schemas"]["QualityRuleId"];
            severity: components["schemas"]["QualitySeverity"];
            /** Title */
            title: string;
        };
        /**
         * DataQualityPageResponse
         * @description One deterministic and bounded current-state findings page.
         */
        DataQualityPageResponse: {
            /** Findings */
            findings: components["schemas"]["DataQualityFinding"][];
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            summary: components["schemas"]["DataQualitySummary"];
            /** Total Findings */
            total_findings: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * DataQualityRemediationResult
         * @description User-safe result for one successfully applied domain mutation.
         */
        DataQualityRemediationResult: {
            action: components["schemas"]["QualityAction"];
            /**
             * Affected Entity Id
             * Format: uuid
             */
            affected_entity_id: string;
            audit_action: components["schemas"]["DataQualityAuditAction"];
            /** Message */
            message: string;
            /**
             * Status
             * @default applied
             * @constant
             */
            status: "applied";
        };
        /**
         * DataQualitySummary
         * @description Unfiltered counts calculated from the current finding set.
         */
        DataQualitySummary: {
            /** Critical Count */
            critical_count: number;
            /** Domain Counts */
            domain_counts: {
                [key: string]: number;
            };
            /** Info Count */
            info_count: number;
            /** Total Findings */
            total_findings: number;
            /** Warning Count */
            warning_count: number;
        };
        DirectQualityRemediation: components["schemas"]["NormalizeRosterOrderRemediation"] | components["schemas"]["RemoveInactivePlayerRemediation"] | components["schemas"]["RemoveInactiveAssistantAssignmentRemediation"];
        /**
         * DismissalType
         * @description Supported batting dismissal outcomes.
         * @enum {string}
         */
        DismissalType: "not out" | "caught" | "bowled" | "lbw" | "run out" | "stumped" | "other";
        /**
         * EventType
         * @description Supported academy calendar event classifications.
         * @enum {string}
         */
        EventType: "practice" | "game" | "miscellaneous";
        /**
         * ExplicitMatchCompletionBoundary
         * @description Points where a capability may accept explicit Match completion.
         * @enum {string}
         */
        ExplicitMatchCompletionBoundary: "none" | "after_completed_innings" | "any_nonterminal_state";
        /**
         * ExternalMatchParticipantRequest
         * @description One academy Team playing a named external opponent.
         */
        ExternalMatchParticipantRequest: {
            /**
             * Academy Side
             * @enum {string}
             */
            academy_side: "home" | "away";
            /**
             * Academy Team Id
             * Format: uuid
             */
            academy_team_id: string;
            /** External Opponent Name */
            external_opponent_name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            participant_type: "external";
        };
        /**
         * ExternalMatchParticipantResponse
         * @description Expanded external participant response.
         */
        ExternalMatchParticipantResponse: {
            /**
             * Academy Side
             * @enum {string}
             */
            academy_side: "home" | "away";
            academy_team: components["schemas"]["MatchTeamReference"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "external";
            /** Opponent Name */
            opponent_name: string;
        };
        /**
         * FieldingPerformance
         * @description Optional fielding metrics for one player in one match.
         */
        FieldingPerformance: {
            /**
             * Catches
             * @default 0
             */
            catches: number;
            /**
             * Dropped Catches
             * @default 0
             */
            dropped_catches: number;
            /** Notes */
            notes?: string | null;
            /**
             * Run Outs
             * @default 0
             */
            run_outs: number;
            /**
             * Stumpings
             * @default 0
             */
            stumpings: number;
        };
        /**
         * FormatCapabilityProfile
         * @description Canonical immutable scoring-capability profile identifiers.
         * @enum {string}
         */
        FormatCapabilityProfile: "T20" | "one-day" | "test" | "other";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InningsCompletionMode
         * @description Capability-listed ways an Innings may complete.
         * @enum {string}
         */
        InningsCompletionMode: "all_out" | "legal_ball_limit" | "target_reached" | "declaration" | "manual";
        /**
         * InningsTransitionType
         * @description Append-only scorer selections anchored in Innings history.
         * @enum {string}
         */
        InningsTransitionType: "innings_started" | "next_batter" | "next_bowler" | "retired_hurt" | "retired_hurt_return" | "innings_completed";
        /**
         * InternalMatchParticipantRequest
         * @description Two academy Teams with explicit home and away sides.
         */
        InternalMatchParticipantRequest: {
            /**
             * Away Team Id
             * Format: uuid
             */
            away_team_id: string;
            /**
             * Home Team Id
             * Format: uuid
             */
            home_team_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            participant_type: "internal";
        };
        /**
         * InternalMatchParticipantResponse
         * @description Expanded internal participant response.
         */
        InternalMatchParticipantResponse: {
            away_team: components["schemas"]["MatchTeamReference"];
            home_team: components["schemas"]["MatchTeamReference"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "internal";
        };
        /**
         * LoginRequest
         * @description Email and plaintext password credentials supplied during login.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MatchCompletionMode
         * @description Supported Match-level completion commands.
         * @enum {string}
         */
        MatchCompletionMode: "derived_result" | "draw" | "declared" | "manual" | "abandonment";
        /**
         * MatchConfigurationRequest
         * @description Atomic fixed-side, participant, and capability configuration command.
         */
        MatchConfigurationRequest: {
            format: components["schemas"]["MatchFormat"];
            /** Match Version Number */
            match_version_number: number;
            /** Participants */
            participants: components["schemas"]["MatchParticipantConfigurationRequest"][];
            policy: components["schemas"]["ScoringPolicyConfigurationRequest"];
            /** Sides */
            sides: components["schemas"]["MatchSideConfigurationRequest"][];
        };
        /** MatchConfigurationResponse */
        MatchConfigurationResponse: {
            blocking_state: components["schemas"]["BlockingStateResponse"];
            /**
             * Configured At
             * Format: date-time
             */
            configured_at: string;
            lifecycle_state: components["schemas"]["MatchLifecycleState"];
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Match Version Number */
            match_version_number: number;
            /** Participants */
            participants: components["schemas"]["src__schemas__scoring__MatchParticipantResponse"][];
            policy: components["schemas"]["ScoringPolicyResponse"];
            scoring_authority: components["schemas"]["ScoringAuthority"];
            /** Sides */
            sides: components["schemas"]["MatchSideResponse"][];
        };
        /**
         * MatchCreate
         * @description Payload for recording a cricket Match.
         */
        MatchCreate: {
            format: components["schemas"]["MatchFormat"];
            /**
             * Match Date
             * Format: date
             */
            match_date: string;
            participants: components["schemas"]["MatchParticipantRequest"];
            /** Result */
            result: string;
            /** Venue */
            venue: string;
        };
        /**
         * MatchFormat
         * @description Supported cricket match formats.
         * @enum {string}
         */
        MatchFormat: "T20" | "one-day" | "test" | "other";
        /**
         * MatchLifecycleState
         * @description Lifecycle values owned by the Match aggregate.
         * @enum {string}
         */
        MatchLifecycleState: "scheduled" | "in_progress" | "completed" | "abandoned" | "correction_reprocessing";
        /**
         * MatchParticipantConfigurationRequest
         * @description Minimal fixed participant identity; account fields are not accepted.
         */
        MatchParticipantConfigurationRequest: {
            /** Batting Order Position */
            batting_order_position: number;
            /** Display Name */
            display_name?: string | null;
            participant_kind: components["schemas"]["MatchParticipantKind"];
            /** Player Id */
            player_id?: string | null;
            side_code: components["schemas"]["MatchSideCode"];
        };
        /**
         * MatchParticipantKind
         * @description Identity source for one fixed Match participant.
         * @enum {string}
         */
        MatchParticipantKind: "internal" | "external";
        MatchParticipantRequest: components["schemas"]["ExternalMatchParticipantRequest"] | components["schemas"]["InternalMatchParticipantRequest"];
        /**
         * MatchResponse
         * @description Complete server-managed Match representation.
         */
        MatchResponse: {
            /** Configured At */
            configured_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            format: components["schemas"]["MatchFormat"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Innings Sequence */
            innings_sequence?: string[];
            /** @default scheduled */
            lifecycle_state: components["schemas"]["MatchLifecycleState"];
            /**
             * Match Date
             * Format: date
             */
            match_date: string;
            participants: components["schemas"]["src__schemas__match__MatchParticipantResponse"];
            /** Result */
            result: string;
            /** @default pending */
            result_code: components["schemas"]["MatchResultCode"];
            /** Result Details */
            result_details?: {
                [key: string]: unknown;
            };
            /** @default legacy_aggregate */
            scoring_authority: components["schemas"]["ScoringAuthority"];
            /** Scoring Participants */
            scoring_participants?: components["schemas"]["src__schemas__scoring__MatchParticipantResponse"][];
            scoring_policy?: components["schemas"]["ScoringPolicyResponse"] | null;
            /** Scoring Sides */
            scoring_sides?: components["schemas"]["MatchSideResponse"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Venue */
            venue: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * MatchResultCode
         * @description Canonical non-terminal and terminal Match result codes.
         * @enum {string}
         */
        MatchResultCode: "pending" | "win_by_runs" | "win_by_wickets" | "tie" | "draw" | "no_result" | "declared" | "manual";
        /**
         * MatchSideCode
         * @description Stable side positions retained from the existing Match boundary.
         * @enum {string}
         */
        MatchSideCode: "home" | "away";
        /**
         * MatchSideConfigurationRequest
         * @description One academy or external side supplied during atomic configuration.
         */
        MatchSideConfigurationRequest: {
            /** Display Name */
            display_name?: string | null;
            side_code: components["schemas"]["MatchSideCode"];
            side_kind: components["schemas"]["MatchSideKind"];
            /** Team Id */
            team_id?: string | null;
        };
        /**
         * MatchSideKind
         * @description Identity source for one configured Match side.
         * @enum {string}
         */
        MatchSideKind: "academy" | "external";
        /** MatchSideResponse */
        MatchSideResponse: {
            /** Display Name Snapshot */
            display_name_snapshot: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            side_code: components["schemas"]["MatchSideCode"];
            side_kind: components["schemas"]["MatchSideKind"];
            /** Team Id */
            team_id: string | null;
        };
        /**
         * MatchTeamReference
         * @description Safe Team identity embedded in participant responses.
         */
        MatchTeamReference: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * MatchUpdate
         * @description Complete Match replacement carrying its OCC version.
         */
        MatchUpdate: {
            format: components["schemas"]["MatchFormat"];
            /**
             * Match Date
             * Format: date
             */
            match_date: string;
            participants: components["schemas"]["MatchParticipantRequest"];
            /** Result */
            result: string;
            /** Venue */
            venue: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * NormalizeRosterOrderRemediation
         * @description Current target metadata for a safe roster-order normalization.
         */
        NormalizeRosterOrderRemediation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "normalize_roster_order";
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /** Expected Team Version */
            expected_team_version: number;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * NormalizeRosterOrderRequest
         * @description Confirmation-gated command for one team's current roster order.
         */
        NormalizeRosterOrderRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "normalize_roster_order";
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Expected Team Version */
            expected_team_version: number;
            /** Finding Id */
            finding_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * PaginatedCoachResponse
         * @description Server-paginated coach collection metadata.
         */
        PaginatedCoachResponse: {
            /** Coaches */
            coaches: components["schemas"]["CoachResponse"][];
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Coaches */
            total_coaches: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PaginatedPlayerAccountResponse
         * @description One bounded page of eligible, unlinked Player-role accounts.
         */
        PaginatedPlayerAccountResponse: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
            /** Total Users */
            total_users: number;
            /** Users */
            users: components["schemas"]["PlayerAccountSnapshot"][];
        };
        /**
         * PaginatedPlayerResponse
         * @description One page of active players with navigation metadata.
         */
        PaginatedPlayerResponse: {
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Players */
            players: components["schemas"]["PlayerResponse"][];
            /** Total Pages */
            total_pages: number;
            /** Total Players */
            total_players: number;
        };
        /**
         * PaginatedTeamResponse
         * @description A stable, server-paginated page of team summaries.
         */
        PaginatedTeamResponse: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Teams */
            teams: components["schemas"]["TeamResponse"][];
            /** Total Pages */
            total_pages: number;
            /** Total Teams */
            total_teams: number;
        };
        /**
         * PlayerAccountAssociationResponse
         * @description Safe result shared by link, unlink, and reassignment mutations.
         */
        PlayerAccountAssociationResponse: {
            account: components["schemas"]["PlayerAccountSnapshot"] | null;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /** Player Version Number */
            player_version_number: number;
        };
        /**
         * PlayerAccountLinkRequest
         * @description Associate one eligible account at the current Player version.
         */
        PlayerAccountLinkRequest: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * PlayerAccountReassignRequest
         * @description Replace an expected association with one eligible account.
         */
        PlayerAccountReassignRequest: {
            /**
             * Expected User Id
             * Format: uuid
             */
            expected_user_id: string;
            /**
             * New User Id
             * Format: uuid
             */
            new_user_id: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * PlayerAccountSnapshot
         * @description Allowlisted account fields safe for the protected linking flow.
         */
        PlayerAccountSnapshot: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Role
             * @constant
             */
            role: "player";
        };
        /**
         * PlayerAccountUnlinkRequest
         * @description Remove one association at the current Player version.
         */
        PlayerAccountUnlinkRequest: {
            /** Version Number */
            version_number: number;
        };
        /**
         * PlayerCreate
         * @description Payload for creating a player profile.
         */
        PlayerCreate: {
            batting_style: components["schemas"]["BattingStyle"];
            /** Bio */
            bio?: string | null;
            bowling_style: components["schemas"]["BowlingStyle"];
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Player Metadata */
            player_metadata?: {
                [key: string]: unknown;
            };
            player_type: components["schemas"]["PlayerType"];
        };
        /**
         * PlayerPerformance
         * @description All supplied performance groups for one player.
         */
        PlayerPerformance: {
            batting?: components["schemas"]["BattingPerformance"] | null;
            bowling?: components["schemas"]["BowlingPerformance"] | null;
            fielding?: components["schemas"]["FieldingPerformance"] | null;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
        };
        /**
         * PlayerResponse
         * @description Complete player projection with bounds for legacy oversized rows.
         *
         *     Valid stored values are returned unchanged. Legacy biographies are projected
         *     to their first 2,000 characters, while legacy metadata that violates current
         *     write bounds is represented as an empty object. Reads never mutate storage.
         */
        PlayerResponse: {
            batting_style: components["schemas"]["BattingStyle"];
            /** Bio */
            bio: string | null;
            bowling_style: components["schemas"]["BowlingStyle"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            /** Player Metadata */
            player_metadata: {
                [key: string]: unknown;
            };
            player_type: components["schemas"]["PlayerType"];
            /** Teams */
            teams?: components["schemas"]["TeamSummary"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * PlayerType
         * @description Supported player roles.
         * @enum {string}
         */
        PlayerType: "batter" | "bowler" | "all-rounder" | "wicket-keeper";
        /**
         * PlayerUpdate
         * @description Partial player update carrying the required OCC version.
         */
        PlayerUpdate: {
            batting_style?: components["schemas"]["BattingStyle"] | null;
            /** Bio */
            bio?: string | null;
            bowling_style?: components["schemas"]["BowlingStyle"] | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Last Name */
            last_name?: string | null;
            /** Player Metadata */
            player_metadata?: {
                [key: string]: unknown;
            } | null;
            player_type?: components["schemas"]["PlayerType"] | null;
            /** Version Number */
            version_number: number;
        };
        /**
         * ProfileUpdate
         * @description Editable profile fields supplied by an authenticated user.
         */
        ProfileUpdate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /**
         * QualityAction
         * @description Direct corrections supported by the initial quality contract.
         * @enum {string}
         */
        QualityAction: "normalize_roster_order" | "remove_inactive_player" | "remove_inactive_assistant_assignment";
        /**
         * QualityDomain
         * @description Allowlisted academy domains evaluated by Data Quality.
         * @enum {string}
         */
        QualityDomain: "players" | "teams" | "rosters" | "coaches" | "calendar";
        /**
         * QualityEntityType
         * @description Entity labels permitted in current-state quality findings.
         * @enum {string}
         */
        QualityEntityType: "player" | "team" | "roster" | "roster_membership" | "coach" | "coach_assignment" | "calendar_event" | "recurrence_series" | "occurrence_exception" | "academy";
        /**
         * QualityRuleId
         * @description Stable identifiers for the initial Data Quality rule catalogue.
         * @enum {string}
         */
        QualityRuleId: "player.active_unassigned" | "player.inactive_rostered" | "player.normalized_identity_duplicate" | "team.roster_below_minimum" | "team.roster_above_maximum" | "roster.order_non_positive" | "roster.order_duplicate" | "roster.order_gap" | "roster.order_non_contiguous" | "team.normalized_name_conflict" | "team.no_assigned_coach" | "coach.sole_head_coach_integrity" | "coach.inactive_assigned" | "coach.active_assistant_unassigned" | "coach.assignment_invalid_role" | "calendar.recurrence_end_before_start" | "calendar.stale_occurrence_exception";
        /**
         * QualitySeverity
         * @description Operational impact levels exposed by Data Quality findings.
         * @enum {string}
         */
        QualitySeverity: "critical" | "warning" | "info";
        /**
         * RagRetrievalErrorResponse
         * @description Sanitized API error envelope.
         */
        RagRetrievalErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * RagRetrievalProvenance
         * @description Allowlisted source identity required for future citations.
         */
        RagRetrievalProvenance: {
            /** Source Entity Id */
            source_entity_id?: string | null;
            /** Source Type */
            source_type: string;
        };
        /**
         * RagRetrievalResponse
         * @description Bounded retrieval response envelope.
         */
        RagRetrievalResponse: {
            /** Limit */
            limit: number;
            /** Results */
            results?: components["schemas"]["RagRetrievalResult"][];
            /** Returned Count */
            returned_count: number;
        };
        /**
         * RagRetrievalResult
         * @description Safe result metadata without vectors or provider response details.
         */
        RagRetrievalResult: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            provenance: components["schemas"]["RagRetrievalProvenance"];
            /** Score */
            score: number;
            /** Source Key */
            source_key: string;
            /** Source Type */
            source_type: string;
            /** Text */
            text: string;
        };
        /**
         * RecentBusinessAuditResponse
         * @description At most four events for Head Coach dashboard activity.
         */
        RecentBusinessAuditResponse: {
            /** Events */
            events: components["schemas"]["BusinessAuditEventResponse"][];
        };
        /**
         * RecurrenceFrequency
         * @description Supported fixed-interval calendar recurrence frequencies.
         * @enum {string}
         */
        RecurrenceFrequency: "weekly" | "yearly";
        /**
         * RecurrenceSeriesResponse
         * @description Persisted recurrence identity and derived rule fields.
         */
        RecurrenceSeriesResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** End Date */
            end_date: string | null;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Month */
            month?: number | null;
            /** Month Day */
            month_day?: number | null;
            /** Occurrence Count */
            occurrence_count?: number | null;
            termination: components["schemas"]["RecurrenceTermination"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weekday */
            weekday?: number | null;
        };
        /**
         * RecurrenceTermination
         * @description Supported ways to terminate a recurring calendar series.
         * @enum {string}
         */
        RecurrenceTermination: "never" | "end_date" | "occurrence_count";
        /**
         * RelatedQualityEntity
         * @description A deterministic related record needed to explain one finding.
         */
        RelatedQualityEntity: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            entity_type: components["schemas"]["QualityEntityType"];
        };
        /**
         * RemoveInactiveAssistantAssignmentRemediation
         * @description Current target metadata for removing one Assistant assignment.
         */
        RemoveInactiveAssistantAssignmentRemediation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_assistant_assignment";
            /**
             * Coach Id
             * Format: uuid
             */
            coach_id: string;
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /** Expected Coach Version */
            expected_coach_version: number;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RemoveInactiveAssistantAssignmentRequest
         * @description Confirmation-gated command for one inactive Assistant assignment.
         */
        RemoveInactiveAssistantAssignmentRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_assistant_assignment";
            /**
             * Coach Id
             * Format: uuid
             */
            coach_id: string;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Expected Coach Version */
            expected_coach_version: number;
            /** Finding Id */
            finding_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RemoveInactivePlayerRemediation
         * @description Current target metadata for removing one inactive membership.
         */
        RemoveInactivePlayerRemediation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_player";
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /** Expected Team Version */
            expected_team_version: number;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RemoveInactivePlayerRequest
         * @description Confirmation-gated command for exactly one inactive membership.
         */
        RemoveInactivePlayerRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "remove_inactive_player";
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Expected Team Version */
            expected_team_version: number;
            /** Finding Id */
            finding_id: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * RoleAwareApiErrorResponse
         * @description Existing non-sensitive API error envelope used by feature operations.
         */
        RoleAwareApiErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * ScopeKind
         * @description Supported audience scope representations for calendar events.
         * @enum {string}
         */
        ScopeKind: "age_group" | "all_academy";
        /**
         * ScoringAuthority
         * @description Authoritative source used for a Match's scoring figures.
         * @enum {string}
         */
        ScoringAuthority: "legacy_aggregate" | "delivery_history";
        /**
         * ScoringDismissalType
         * @description Current public scoring dismissal vocabulary.
         *
         *     Reserved future dismissals are deliberately absent so schema parsing fails
         *     closed until a later capability version introduces them.
         * @enum {string}
         */
        ScoringDismissalType: "bowled" | "caught" | "caught_and_bowled" | "lbw" | "run_out" | "stumped" | "hit_wicket" | "retired_out";
        /**
         * ScoringPolicyConfigurationRequest
         * @description Capability selection plus only the policy values a profile permits.
         */
        ScoringPolicyConfigurationRequest: {
            /** Allow Declaration */
            allow_declaration?: boolean | null;
            /** Allow Draw */
            allow_draw?: boolean | null;
            /** Allow Manual Completion */
            allow_manual_completion?: boolean | null;
            /** Allowed Dismissal Types */
            allowed_dismissal_types?: components["schemas"]["ScoringDismissalType"][] | null;
            /** Allowed Innings Completion Modes */
            allowed_innings_completion_modes?: components["schemas"]["InningsCompletionMode"][] | null;
            /** Allowed Match Completion Modes */
            allowed_match_completion_modes?: components["schemas"]["MatchCompletionMode"][] | null;
            /** Allowed Result Codes */
            allowed_result_codes?: components["schemas"]["MatchResultCode"][] | null;
            /** Allowed Transition Types */
            allowed_transition_types?: components["schemas"]["InningsTransitionType"][] | null;
            /** Bowler Quota Legal Balls */
            bowler_quota_legal_balls?: number | null;
            capability_profile: components["schemas"]["FormatCapabilityProfile"];
            /**
             * Capability Version
             * @default 1
             */
            capability_version: number;
            /** Consecutive Overs Prohibited */
            consecutive_overs_prohibited?: boolean | null;
            explicit_match_completion_boundary?: components["schemas"]["ExplicitMatchCompletionBoundary"] | null;
            /** Innings Per Side */
            innings_per_side?: number | null;
            /** Innings Sequence */
            innings_sequence: components["schemas"]["MatchSideCode"][];
            /** Legal Ball Limit */
            legal_ball_limit?: number | null;
            /** Over Length Legal Balls */
            over_length_legal_balls?: number | null;
            policy_code: components["schemas"]["MatchFormat"];
            target_mode?: components["schemas"]["TargetMode"] | null;
            /** Wicket Limit */
            wicket_limit?: number | null;
        };
        /** ScoringPolicyResponse */
        ScoringPolicyResponse: {
            /** Allow Declaration */
            allow_declaration: boolean;
            /** Allow Draw */
            allow_draw: boolean;
            /** Allow Manual Completion */
            allow_manual_completion: boolean;
            /** Allowed Dismissal Types */
            allowed_dismissal_types: components["schemas"]["ScoringDismissalType"][];
            /** Allowed Innings Completion Modes */
            allowed_innings_completion_modes: components["schemas"]["InningsCompletionMode"][];
            /** Allowed Match Completion Modes */
            allowed_match_completion_modes: components["schemas"]["MatchCompletionMode"][];
            /** Allowed Result Codes */
            allowed_result_codes: components["schemas"]["MatchResultCode"][];
            /** Allowed Transition Types */
            allowed_transition_types: components["schemas"]["InningsTransitionType"][];
            /** Bowler Quota Legal Balls */
            bowler_quota_legal_balls?: number | null;
            capability_profile: components["schemas"]["FormatCapabilityProfile"];
            /** Capability Version */
            capability_version: number;
            /** Consecutive Overs Prohibited */
            consecutive_overs_prohibited: boolean;
            explicit_match_completion_boundary: components["schemas"]["ExplicitMatchCompletionBoundary"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Innings Per Side */
            innings_per_side: number;
            /** Innings Sequence */
            innings_sequence: components["schemas"]["MatchSideCode"][];
            /** Legal Ball Limit */
            legal_ball_limit?: number | null;
            /** Over Length Legal Balls */
            over_length_legal_balls: number;
            policy_code: components["schemas"]["MatchFormat"];
            /** Policy Version */
            policy_version: number;
            target_mode: components["schemas"]["TargetMode"];
            /** Version Number */
            version_number: number;
            /** Wicket Limit */
            wicket_limit: number;
        };
        /**
         * TargetMode
         * @description Capability-defined target derivation behavior.
         * @enum {string}
         */
        TargetMode: "prior_innings_plus_one" | "none";
        /**
         * TeamCreate
         * @description Validated payload for creating a complete team roster.
         */
        TeamCreate: {
            age_group: components["schemas"]["AgeGroup"];
            /** Name */
            name: string;
            /** Player Ids */
            player_ids: string[];
        };
        /**
         * TeamPlayerResponse
         * @description Legacy public representation of a single team membership.
         */
        TeamPlayerResponse: {
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * TeamResponse
         * @description Team summary used in lists and mutation responses.
         */
        TeamResponse: {
            age_group: components["schemas"]["AgeGroup"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Player Count
             * @default 0
             */
            player_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * TeamRosterPlayerResponse
         * @description A roster entry, including inactive historical members.
         */
        TeamRosterPlayerResponse: {
            /** First Name */
            first_name: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /** Roster Order */
            roster_order: number;
        };
        /**
         * TeamRosterResponse
         * @description Ordered players belonging to one team.
         */
        TeamRosterResponse: {
            /** Players */
            players: components["schemas"]["TeamRosterPlayerResponse"][];
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
        };
        /**
         * TeamSummary
         * @description Lightweight team identity embedded in player responses.
         */
        TeamSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * TeamUpdate
         * @description Complete replacement payload carrying the OCC version.
         */
        TeamUpdate: {
            age_group: components["schemas"]["AgeGroup"];
            /** Name */
            name: string;
            /** Player Ids */
            player_ids: string[];
            /** Version Number */
            version_number: number;
        };
        /**
         * TokenResponse
         * @description Bearer access token returned after login or refresh.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /**
         * UserCreate
         * @description Payload for creating a user account.
         */
        UserCreate: {
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Password */
            password: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserPasswordChange
         * @description Payload for replacing an account password.
         */
        UserPasswordChange: {
            /** New Password */
            new_password: string;
        };
        /**
         * UserResponse
         * @description Public account representation, intentionally excluding the password hash.
         */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name: string;
            role: components["schemas"]["UserRole"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version Number */
            version_number: number;
        };
        /**
         * UserRole
         * @description Supported user account roles.
         * @enum {string}
         */
        UserRole: "head coach" | "assistant coach" | "player";
        /**
         * UserRoleUpdate
         * @description Payload for a head coach changing an account's role.
         */
        UserRoleUpdate: {
            role: components["schemas"]["UserRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        src__schemas__match__MatchParticipantResponse: components["schemas"]["ExternalMatchParticipantResponse"] | components["schemas"]["InternalMatchParticipantResponse"];
        /** MatchParticipantResponse */
        src__schemas__scoring__MatchParticipantResponse: {
            /** Batting Order Position */
            batting_order_position: number;
            /** Display Name Snapshot */
            display_name_snapshot: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            participant_kind: components["schemas"]["MatchParticipantKind"];
            /** Player Id */
            player_id: string | null;
            /**
             * Side Id
             * Format: uuid
             */
            side_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_data_quality_api_v1_data_quality_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                severity?: components["schemas"]["QualitySeverity"] | null;
                domain?: components["schemas"]["QualityDomain"] | null;
                rule_id?: components["schemas"]["QualityRuleId"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_data_quality_remediation: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NormalizeRosterOrderRequest"] | components["schemas"]["RemoveInactivePlayerRequest"] | components["schemas"]["RemoveInactiveAssistantAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityRemediationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
